
spring:
  profiles:
    active: develop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/develop_schema?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

---

spring:
  profiles:
    active: production

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://103.244.111.30:3306/develop_schema?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gmc
    password: Gmc@1234!
